name: Latest YouTube Videos
on:
  schedule:

    - cron: '0 10 * * *'
    # Runs every hour
    # - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCoC47do520os_4DBMEFGg4A"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          date_format: "mmm d, yyyy"
          template: "<tr><td><a href=\"$url\"><img width=\"140px\" src=\"https://i.ytimg.com/vi/$videoId/mqdefault.jpg\"></a></td>$newline<td><a href=\"$url\">$title</a><br/>$date</td></tr>$newline"
